### ISSUE TITLE
allow configurable keepalived container image with cephadm

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/cephci#1002]
Similar to https://github.com/red-hat-storage/cephci/issues/431 , we're introducing a new container image: keepalived.

The `/usr/sbin/cephadm` script will hardcode `DEFAULT_KEEPALIVED_IMAGE = 'registry.redhat.io/rhceph/keepalived-rhel8:latest'`, but we have not shipped to that location on registry.redhat.io yet.

In the meantime, before we ship this to the public registry, we need a way to override the keepalived image location to use Red Hat's internal registry location.

**Comment by psathyan** [comment]
Thanks @ktdreyer for the heads up. We will plan to address this requirement with priority

**Comment by ktdreyer** [comment]
Thanks. The relevant BZ is https://bugzilla.redhat.com/2007648

**Comment by ktdreyer** [comment]
`registry-proxy.engineering.redhat.com/rh-osbs/keepalived:2.1.5-1` is the override URL to use for now
