### ISSUE TITLE
renaming upgrade suites based on osd scenario type/upgrade path

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#101]
https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/upgrades/upgrade_3.x_to_4.x.yaml#L19 

osd _scenario shud be lvm ( should we do upgrade with mixed_lvm_configs: True @VasishtaShastry @rakeshgm )
#74  can you retest this pl , by having correct config @Ameenasuhani , and post the cli used, be specific on build versions unlike 3.0 /may be 3.3
 

- [ ] add the suite/job to ceph-jenkins p1 jobs pipeline

**Comment by XDsubhash** [comment]
@skanta is working on container upgrade

**Comment by Ameenasuhani** [comment]
Just to confirm is it necessary the osd_scenario has to be lvm?
Because during upgrade any osd_scenario i.e collocated or non-collocated is migrated to lvm
(3.x to 4.x)

**Comment by Ameenasuhani** [comment]
I believe you are pointing to make changes https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/upgrades/upgrade_3.x_to_4.x.yaml#L45

**Comment by XDsubhash** [comment]
yes, the osd_scenarios has to be lvm, we stopped testing ceph-disk long back , i overlooked the config in the pr, looking at log in #74 http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1583208270845/ceph_ansible_install_rhcs_3_stable_0.log , it is not creating any lvm osds

`Because during upgrade any osd_scenario i.e collocated or non-collocated is migrated to lvm
(3.x to 4.x)` can you elaborate on this @Ameenasuhani ?

**Comment by XDsubhash** [comment]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1583208270845/ceph_ansible_0.log , i do see TASK [activate scanned ceph-disk osds and migrate to ceph-volume if deploying nautilus] in upgrade log

**Comment by Ameenasuhani** [comment]
@XDsubhash In http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1583208270845/ceph_ansible_0.log as you can see in this log the ceph disk is migrated ceph volume, during upgrade from 3.x to 4.x the ceph disk are implicitly migrated to ceph volume
Reference bug:
- https://bugzilla.redhat.com/show_bug.cgi?id=1656460
-https://bugzilla.redhat.com/show_bug.cgi?id=1656454

**Comment by rakeshgm** [comment]
@XDsubhash for now let @Ameenasuhani work on this @SrinivasaBharath is taking up other work

**Comment by XDsubhash** [comment]
> @XDsubhash In http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1583208270845/ceph_ansible_0.log as you can see in this log the ceph disk is migrated ceph volume, during upgrade from 3.x to 4.x the ceph disk are implicitly migrated to ceph volume
> Reference bug:
> 
> * https://bugzilla.redhat.com/show_bug.cgi?id=1656460
>   -https://bugzilla.redhat.com/show_bug.cgi?id=1656454

So you have automated above bug in cephci, You can specify that in the suite yaml  TC description.(add polarion if there is one for this scenario)
For the upgrade scenario's part of release 3.x lvm to 4.x you can create a another suite file , with appropriate ansible configs and name the suite yamls specifically(eg 3.x_GA_lvm_to_4.x _latest_lvm, for the above bugs eg 3.x_GA_ceph-disk_to_4.x_latest_lvm_implicit_migrate)Include specific info in file naming and TC descriptions

**Comment by XDsubhash** [comment]
CLI used here for upgrade as per @Ameenasuhani python run.py --rhbuild 4.0-rhel-7 --global-conf conf/nautilus/upgrades/upgrade_3.x_to_4.x.yaml --osp-cred osp/osp-cred.yaml --inventory conf/inventory/rhel-7.7-server-x86_64.yaml --suite suites/nautilus/upgrades/upgrade_3.x_to_4.x.yaml --log-level in
fo --store --ignore-latest-container
