### ISSUE TITLE
rados bench stuck in infinite loop

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#103]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-ansible-sanity-3.3-rhel7.7/1/console

runs IO indefinitely , som issue with rados bench cli or script( intermittent )
debug:
is cluster getting full the issue ?not sure as it running past the time mentioned 360 sec , https://github.com/red-hat-storage/cephci/blob/master/tests/radosbench.py#L51

**Comment by rakeshgm** [comment]
@Manohar-Murthy can you look into this.

**Comment by XDsubhash** [comment]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-ansible-sanity-4.1-rhel7.8/40/console  passed case

**Comment by XDsubhash** [comment]
@Manohar-Murthy any update on this?can you send a draft PR (WIP) so we can dicuss in github if you are facing any issue in fixing

**Comment by SrinivasaBharath** [comment]
Script failing at https://github.com/red-hat-storage/cephci/blob/master/tests/test_ansible.py#L73.

**Comment by SrinivasaBharath** [comment]
Test case - "rbd cli image" is getting failed.
This bug depends on- https://github.com/red-hat-storage/ceph-qe-scripts/blob/master/rbd/system/cli/rbd_cli_image.py script.

The rbd_cli_image.py internally  calls
 1. https://github.com/red-hat-storage/ceph-qe-scripts/blob/master/rbd/system/cli/parameters.py
 2. https://github.com/red-hat-storage/ceph-qe-scripts/blob/master/rbd/utils/utils.py 

In both files there is no code exit for  ceph version-4(nautilus).Here are the findings-
  
   1. https://github.com/red-hat-storage/ceph-qe-scripts/blob/master/rbd/utils/utils.py#L12.
       In the above method no code entry for the nautilus    
   2. stripe_v4, io_type_v4 and export_format_v4 entries  not exist in         
        https://github.com/red-hat-storage/ceph-qe-scripts/blob/master/rbd/system/cli/parameters.py file

**Comment by SrinivasaBharath** [comment]
Couple of issues failed in the above mentioned job link-
https://github.com/red-hat-storage/cephci/issues/103#issuecomment-618938313
Failed testcase list-
                 1.rbd cli image 
                 2.rbd cli snap_clone
                 3.rbd cli misc
                4.ceph ansible
rbd issues are depended on-https://github.com/red-hat-storage/cephci/issues/86.
The fix is change python to python3 -https://github.com/red-hat-storage/cephci/blob/master/tests/rbd_system.py#L29

**Comment by SrinivasaBharath** [comment]
The rados command which is running to infinite loop is-
https://github.com/red-hat-storage/cephci/blob/master/tests/radosbench.py#L53
This command executes the write test on newly created pool. 

Analysis:
Following command executed in  anode.
  sudo rados --no-log-to-stderr  -b 4194304 -p test_pool58 bench 360 write
 This command Maintaining 16 concurrent writes of 4194304 bytes to objects of size 4194304 for up to 360 seconds or 0 objects. After executing this noticed that pools are getting full.
[cephuser@ceph-bharath-1591873446367-node9-clientnfs ~]$ sudo ceph -s
  cluster:
    id:     9af5549a-3315-4cb5-a973-a53d21acdad3
    health: HEALTH_ERR
            2 backfillfull osd(s)
            4 osds down
            4 nearfull osd(s)
            8 pool(s) backfillfull
            1/18949 objects unfound (0.005%)
            Reduced data availability: 47 pgs inactive
            Possible data damage: 1 pg recovery_unfound
            Degraded data redundancy: 13273/56847 objects degraded (23.349%), 122 pgs degraded, 304 pgs undersized
            application not enabled on 1 pool(s)
            39 daemons have recently crashed
 
  services:
    mon:     3 daemons, quorum ceph-bharath-1591873446367-node2-monmds,ceph-bharath-1591873446367-node6-monrgw,ceph-bharath-1591873446367-node1-monmgrinstaller (age 3d)
    mgr:     ceph-bharath-1591873446367-node1-monmgrinstaller(active, since 3d)
    mds:     cephfs:1 {0=ceph-bharath-1591873446367-node7-mds=up:active} 1 up:standby
    osd:     28 osds: 18 up (since 3m), 22 in (since 32m)
    rgw:     2 daemons active (ceph-bharath-1591873446367-node6-monrgw.rgw0, ceph-bharath-1591873446367-node8-rgw.rgw0)
    rgw-nfs: 1 daemon active (ceph-bharath-1591873446367-node9-clientnfs)
 
  task status:
    scrub status:
        mds.ceph-bharath-1591873446367-node7-mds: idle
 
  data:
    pools:   8 pools, 576 pgs
    objects: 18.95k objects, 73 GiB
    usage:   246 GiB used, 36 GiB / 282 GiB avail
    pgs:     8.160% pgs not active
             13273/56847 objects degraded (23.349%)
             1/18949 objects unfound (0.005%)
             272 active+clean
             151 active+undersized
             105 active+undersized+degraded
             31  undersized+peered
             16  undersized+degraded+peered
             1   active+recovery_unfound+undersized+degraded

**Comment by SrinivasaBharath** [comment]
This  issue depnds on the bug - https://bugzilla.redhat.com/show_bug.cgi?id=1848016

**Comment by SrinivasaBharath** [comment]
Issue resolved with wrokaround.
PR-  https://github.com/red-hat-storage/cephci/pull/141

**Comment by SrinivasaBharath** [comment]
Issue fixed hence closing the PR.
