### ISSUE TITLE
Need functionality to fetch the state of the test and skip test if passed for reruns

### ISSUE THREAD

**Issue by neha-gangadhar** [red-hat-storage/cephci#1038]
If suite YAML has 3 tests ( pre_req, deploy, configure_client) but the config file did not have the proper node details for configure client. In such cases,
test1 - pre-req -> pass
test2 - deploy cluster -> pass
test3 -> configure client -> fails. 

User needs to edit the suite yaml and remove all the passed tests and only have the failed test to rerun the test. 
Instead, If the node details is properly updated in the config YAML and rerun is initiated, based on the test result state the framework can decide to skip the passed test. And run only the failed ones. 

This will enable the user to have very less modifications made in the YAML files.

**Comment by psathyan** [comment]
@neha-gangadhar this is a good suggestion. 

I agree that we don't have the ability to run a specific test case. IMO, we should use test frameworks like `pytest` or `robot` to get access to a larger feature set

**Comment by psathyan** [comment]
As part of different enhancement, we wanted to break down the test cases into modular ones which then can be easily plugged to a larger set. 

This feature is already implemented but does not have a larger acceptance rate.

With that being said, I still believe we should be able to run a set of tests or a specific one.
