### ISSUE TITLE
osd throwing assert, not coming up sometimes on rhel7.8 

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#105]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-ansible-sanity-4.1-rhel7.8/39/consoleFull

https://bugzilla.redhat.com/show_bug.cgi?id=1822134#c18

**Comment by XDsubhash** [comment]
probable udev/systemd race condition.

**Comment by XDsubhash** [comment]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-ansible-sanity-4.1-rhel8.1/45/console

**Comment by XDsubhash** [comment]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-ansible-sanity-4.1-rhel8.1/44/console

**Comment by XDsubhash** [comment]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-ansible-sanity-4.1-rhel7.8/40/console

**Comment by Ameenasuhani** [comment]
Setting  ceph_stable_release: nautilus is inducing this osd failure (https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/ansible/sanity_ceph_ansible.yaml#L16) upon excluding this the runs have passed

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1614714802916/ceph_ansible_0.log
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1614716601570/ceph_ansible_0.log

BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1934213

**Comment by psathyan** [comment]
@Ameenasuhani do we want to keep this issue still open

**Comment by psathyan** [comment]
The BZ is closed won't fix hence I don't see a point in keeping this issue open at our end.
