### ISSUE TITLE
rhcs4 ubuntu repos not found in rhbuild.yaml

### ISSUE THREAD

**Issue by Ameenasuhani** [red-hat-storage/cephci#106]
Redundant ubuntu repos found in rhbuild.yaml for nautilus 
eg: https://github.com/red-hat-storage/cephci/blob/master/rhbuild.yaml#L26

**Comment by XDsubhash** [comment]
rhcs4 not supported on ubuntu at the moment

**Comment by Ameenasuhani** [comment]
The issue has been fixed here https://github.com/red-hat-storage/cephci/pull/161
