### ISSUE TITLE
--rhbuild is mandatory but not always used

### ISSUE THREAD

**Issue by andrewschoen** [red-hat-storage/cephci#1075]
The ``--rhbuild`` flag is required, but it is not always used. If the ``--hotfix-repo`` or any of the ``--docker-*`` flags are used ``--rhbuild`` becomes a noop. Is there a way we can not require ``--rhbuid`` in that situation?

**Comment by ktdreyer** [comment]
For context, we use the `--hotfix-repo` and `--docker-*` flags when we test all our work-in-progress Ceph builds in GitLab Merge Requests

**Comment by psathyan** [comment]
I agree with the assessment that `rhbuild` is not a mandatory option in some scenarios. Most of our tests use it to switch code paths based on the release. Making it optional wouldn't break the implementation but would fail late.

Other than that, I don't see a reason why `--rhbuild` cannot be made optional.

**Comment by psathyan** [comment]
After further examination, we would not be able fix this issue. Allowing it to be optional breaks a lot of code paths.

**Comment by psathyan** [comment]
As our scope is expanding, we have observed that this option has to be made optional. Hence, removing the wontfix label
