### ISSUE TITLE
 containerizing rados suite ( no authentic way)

### ISSUE THREAD

**Issue by subhashp7i** [red-hat-storage/cephci#108]
* running ceph-objectstore tool tests in container deploys is not possible as the osd container service needs to be stopped
#89
rados suite, https://bugzilla.redhat.com/show_bug.cgi?id=1811910 https://bugzilla.redhat.com/show_bug.cgi?id=1632494 , no authentic way 
* there is a workaround implemented by running a proxy container to access osd data and corrupt it (fails currently script issue) if needed to implement the hack ,have to work on it

**Comment by rakeshgm** [comment]
can anyone from @red-hat-storage/ceph-qe-rados take a look at it.
