### ISSUE TITLE
--reuse option is not working for upgrades

### ISSUE THREAD

**Issue by Ameenasuhani** [red-hat-storage/cephci#1101]
--reuse option is not working with upgrades

1. Because of this variable https://github.com/red-hat-storage/cephci/blob/master/tests/ceph_ansible/test_ansible_upgrade.py#L23

2. with recent version 2changes 
https://github.com/red-hat-storage/cephci/blob/master/ceph/ceph.py#L387

**Comment by HaruChebrolu** [comment]
Closing this as its a duplicate of https://github.com/red-hat-storage/cephci/issues/978

**Comment by Ameenasuhani** [comment]
@HaruChebrolu #978 addresses the 
>>2. with recent version 2changes
>>https://github.com/red-hat-storage/cephci/blob/master/ceph/ceph.py#L387

but prev_install_version variable is still an issue while using --reuse option so re-opening the issue

**Comment by psathyan** [comment]
At present, `reuse` preserves the cluster state and not the test run state. `test[install_version]` is being set by the deployment script which could have been run earlier. This would lead to `AttributeError` when executed with `reuse` CLI option.

With that being said, this is a valid scenario which has to be tackled. We could find out the RHCS version dynamically to avoid this exception. This would be a more reliable way.

**Comment by Ameenasuhani** [comment]
logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-XNE9SB/
