### ISSUE TITLE
[test_ansible_upgrade.py] : Need change at compare ceph versions.

### ISSUE THREAD

**Issue by sunilkumarn417** [red-hat-storage/cephci#1135]
Currently each container in containerized cluster and ceph services at each node in RPM based cluster are checked to find out daemon versions at comparison. 

Comparing ceph versions from **pre**-and-**post**-upgrade state can be done using,
- `ceph versions` command which provides each and every ceph ceph daemon count with respective version.

**Comment by psathyan** [comment]
I agree we should move to use `ceph versions`... however we would also need to have `expected` list. This would allow us to compare/verify the expected results.
