### ISSUE TITLE
flake8 new version checks F522

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#119]
======================== 8 passed, 7 warnings in 0.52s =========================
py37 run-test: commands[1] | flake8
./tests/radosbench.py:54:0: F522 '...'.format(...) has unused named argument(s): name
./tests/cephfs/cephfs_utils.py:1067:0: F522 '...'.format(...) has unused named argument(s): mon_ip3
ERROR: InvocationError for command /home/travis/build/red-hat-storage/cephci/.tox/py37/bin/flake8 (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py37: commands failed
The command "tox" exited with 1.

changed from travis CI build 161-162

* ignoring the check for now , need to fix variables in above two scripts and renable F522

**Comment by XDsubhash** [comment]
#117

**Comment by rakeshgm** [comment]
fix merged [#117](https://github.com/red-hat-storage/cephci/pull/117)

**Comment by XDsubhash** [comment]
@rakeshgm what do you think abt having F522 check ?| F522 | ``.format(...)`` unused named arguments , should we ignore it forever?
https://github.com/PyCQA/flake8/commit/76eeccad89ac83d7049ec7ebb10776609f7a103d#diff-3c5febb51a1fbda97991ce34cd218a87

**Comment by rakeshgm** [comment]
@XDsubhash we need to fix many tox issues, one such example is `yaml.load()` which deprecated. we can clean up once and for all, and remove `F22` check when we handle the cleanup.

**Comment by XDsubhash** [comment]
@rakeshgm i believe flake8 semantic checks are different to python functionailty(yaml safe load) , may be we can track flake8 checks here in this issue as we only have the above 2 script issues in whole repo.

**Comment by XDsubhash** [comment]
#103
