### ISSUE TITLE
In 5x, Consider all devices in single host for deployment of OSDs.

### ISSUE THREAD

**Issue by sunilkumarn417** [red-hat-storage/cephci#1204]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by psathyan** [comment]
Not sure what is the ask here.

Currently, we don't have a method or module that would dynamically fetch the devices as we expect it to be driven from the test side. Introducing this at SDK layer would prevent negative testing.

**Comment by sunilkumarn417** [comment]
It is already implemented, OSD deployment on selected/specific node(s).
https://github.com/red-hat-storage/cephci/blob/master/suites/pacific/cephadm/tier-1_5-1_service-apply-spec.yaml#L143-L160

Marking this as closed.
