### ISSUE TITLE
Adding OSD's based on cluster nodes and  node device paths

### ISSUE THREAD

**Issue by SrinivasaBharath** [red-hat-storage/cephci#1205]
1. Adding the OSD's based on the nodes that exist in the cluster.
    Example:  In the following cluster add the OSD's based on the nodes that exist in the cluster.
            
                              [ceph: root@depressa008 /]# ceph orch host ls
                              HOST         ADDR          LABELS  STATUS  
                              depressa008  10.1.172.208  _admin          
                              depressa009  10.1.172.209                  
                              depressa010  10.1.172.210                  
                              depressa011  10.1.172.211                  
                              [ceph: root@depressa008 /]#
2.Adding the OSD's based on the node device path
    Example:
      [ceph: root@depressa008 /]# lsblk
NAME                                                                                                  MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                                                                                                     8:0    0 447.1G  0 disk 
`-sda1                                                                                                  8:1    0 447.1G  0 part /rootfs
sdb                                                                                                     8:16   0     7T  0 disk 
`-ceph--fc33aa06--f08d--4fcb--94c5--da709e1caa5f-osd--block--9111e195--a42a--4986--8821--a5ef6d9d5066 253:0    0     7T  0 lvm  
sdc                                                                                                     8:32   0     7T  0 disk 
sdd                                                                                                     8:48   0     7T  0 disk 
nvme1n1                                                                                               259:0    0 349.3G  0 disk 
nvme0n1                                                                                               259:1    0 349.3G  0 disk 
`-ceph--2cee31e8--47df--4ab5--a651--851d9232955a-osd--block--1b53430a--b559--4d22--8cb2--ec165da87f30 253:1    0 349.3G  0 lvm  
[ceph: root@depressa008 /]#

**Comment by psathyan** [comment]
This needs to come from the test module or workflow layer as the support exists already....

**Comment by sunilkumarn417** [comment]
https://github.com/red-hat-storage/cephci/pull/1590/files
