### ISSUE TITLE
[RFE]: Improve/enhance subscription-manager handling

### ISSUE THREAD

**Issue by Ameenasuhani** [red-hat-storage/cephci#1208]
**Is your feature request related to a problem? Please describe.**

The pool id used with subscription fails with cdn credentials as
`This system has no repositories available through subscriptions.`

Similarly when other credentials  other then default qa are used user has to manually modify the script to pass pool-id
https://github.com/red-hat-storage/cephci/blob/master/tests/misc_env/install_prereq.py#L190-L202

**Describe the solution you'd like**
Enhance the way pool-id is passed during runs and subscription-manager is being managed in the code

**Describe alternatives you've considered**

**Additional context**
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-LSGG7V/Install_ceph_pre-requisites_0.log

**Comment by psathyan** [comment]
@Ameenasuhani Thanks for raising this issue.

I agree that we should be able to pass the access information via a configuration or CLI. We did plan this as part of our v2 activity but it never got off...

**Comment by sunilkumarn417** [comment]
SCA(simple content access) is enabled. No need of attaching a pool.

**Comment by sunilkumarn417** [comment]
https://github.com/red-hat-storage/cephci/pull/1928
