### ISSUE TITLE
improve and fix reuse cli arg

### ISSUE THREAD

**Issue by subhashp7i** [red-hat-storage/cephci#122]
* there is some workaround needed for --reuse cli arg like setting clients=None ( do rca on why its needed and can it effect other scripts?)
* document in README on how to use REUSEwith snapshots
* improve the function to auto pick the latest snapshot avaiable in rerun dir (without need to **always** specifying manually) and probably its better to have/retain the manual snapshot select option

**Comment by XDsubhash** [comment]
cluster triggered with --store arg ( will store snapshots in rerun dir)

workaround:(after cli trigger with --store arg included)

https://github.com/red-hat-storage/cephci/blob/master/run.py#L550 make clients=None

and use reuse cli arg below to use the above deployed cluster (to run any/set of specific tests `n` number of times as long env is compatible)

have below arg added to the cli
--reuse rerun/<latest-snapshot-file>   (no need to have --store arg now, likely usecase you'll uncomment install_pre_req and cluster install tasks in suite file and will have custom task)

**Comment by psathyan** [comment]
Can we document the usage and add notes on failure cases?

**Comment by tintumathew10** [comment]
code is merged
