### ISSUE TITLE
update polarion IDs for the automated tests in all suites

### ISSUE THREAD

**Issue by subhashp7i** [red-hat-storage/cephci#126]
* update polarion IDs for the automated tests in all suites
* what abt automated bugzilla TC's ? how to track the results of those , wont be reported in polarion

**Comment by Ameenasuhani** [comment]
@XDsubhash We need to create a test case for upgrade scenario from 3.x to 4.x on rhel7(https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/upgrades/upgrade_3.x_to_4.x.yaml)
