### ISSUE TITLE
RGW containerized suit is failing for RHCS 4.1

### ISSUE THREAD

**Issue by udaysk23** [red-hat-storage/cephci#128]
- rgw containerized suite might needs couple fixes in cephci to pass for container deployment

- Script is not able to capture rgw container name

**Comment by VasishtaShastry** [comment]
@udaysk23 
Can we please have the error message here?
I'm facing issues with 4.1.z1 cluster deployment with containerized sanity ansible ?
I'm not sure whether we are facing same issue ?

**Comment by udaysk23** [comment]
https://github.com/red-hat-storage/cephci/pull/151

Above PR fixed this issue. Closing this issue now
