### ISSUE TITLE
Bug: Set "mon_allow_pool_delete" for all releases <4.x in rbd_utils.py

### ISSUE THREAD

**Issue by pdhiran** [red-hat-storage/cephci#1293]
The Pool deletion process in ceph needs "mon_allow_pool_delete" flag set which is designed as a safety net while pool deletion. this has been introduced since 5.x . 

With the QA team running upstream tests ( RHCS version 6 ), due to the check implemented here in RBD utils, the test runs would fail.

https://github.com/red-hat-storage/cephci/blob/85d30bad2b08c34039e96aaf2feca7824378e967/tests/rbd/rbd_utils.py#L204

Fail log run on 6.0 : http://magna002.ceph.redhat.com/ceph-qe-logs/pawan/cephci-run-S0R3TL/rbd-io_0.log

we can improve the checks made here.

Also, the cmd ` ceph config set ` is dynamic. There is no need for restart of mon daemons required here. ( it would be a bug if restart is required ). The restart step can be removed.

https://github.com/red-hat-storage/cephci/blob/85d30bad2b08c34039e96aaf2feca7824378e967/tests/rbd/rbd_utils.py#L206

**Comment by psathyan** [comment]
Thanks for pointing it out... I think this should be handled when we have RHCS 6.0 support. 

However, if it is required for upstream... please plan to include this change
