### ISSUE TITLE
[RFE] Handling negative test cases in workflow managers (ex: test_rbdv2)

### ISSUE THREAD

**Issue by VasishtaShastry** [red-hat-storage/cephci#1357]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

There are some test cases on negative scenarios. We need to read out put and pass certain testcases if methods return failure.
Example:
IO on rbd image in secondary state should fail.
So if we handle at sdk layer, sdk layer should return true despite command failure
if we handle it at workflow layer, we need to return True despite fails from sdk layer

**Describe the solution you'd like**

We need to read out put and pass certain testcases if methods return failure.

**Describe alternatives you've considered**
None as of now

**Additional context**

**Comment by psathyan** [comment]
@VasishtaShastry Would you be able to elaborate on the issue?

If the method is an interface to the command, then it should return what the command has provided or returned. If a method is a set of instructions calling multiple interfaces then, it should return what it was intended by the implementer. 

This way we can use the interface to support all scenarios arising when it is being called.

**Comment by VasishtaShastry** [comment]
Sorry for the belated update
Closing this ticket for now as workflow layer is not planned in repository as of now. (This issue was created when workflow layer was planned to be added in cephci)
