### ISSUE TITLE
interop suite  TC failure ( rbd rhcs3)

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#140]
https://interop-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/ceph-3.3-rhel-7/17/artifact/.results/artifacts/ceph-test-driver-m2cbp/cephci-run-1592574854168/rbd_cli_image_0.log

**Comment by XDsubhash** [comment]
@harishmunjulur @Gopi-Patta can you take a look at this failure?

**Comment by harishmunjulur** [comment]
https://github.com/red-hat-storage/cephci/pull/143

**Comment by harishmunjulur** [comment]
We are seeing cache issues with one of the tests. We have changed the order of tests to confirm this. Currently all the tests are passing. Will add the final logs and update soon.

**Comment by Gopi-Patta** [comment]
We are seeing some issue(may be cache) with existing order and passing after changing order. here are the logs:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1594788666462/

**Comment by harishmunjulur** [comment]
tests are passing
