### ISSUE TITLE
Remove apache-arrow.repo for baremetal deployments to go smooth from cephci.

### ISSUE THREAD

**Issue by viduship** [red-hat-storage/cephci#1429]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by viduship** [comment]
Remove apache-arrow.repo for bare-metal deployments to go smooth from cephci.

apache arrow repos successful installation of cephadm ansible, and it is present in any freshly re-imaged machines.

**Comment by psathyan** [comment]
Closing this issue as the PR that addresses it has been merged by the reporter
https://github.com/red-hat-storage/cephci/blob/master/tests/misc_env/install_prereq.py#L122
