### ISSUE TITLE
Add support of FIPS enabled cluster

### ISSUE THREAD

**Issue by udaysk23** [red-hat-storage/cephci#1494]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by psathyan** [comment]
After reviewing the document https://access.redhat.com/documentation/eses/red_hat_enterprise_linux/9/html/security_hardening/assembly_installing-the-system-in-fips-mode_security-hardening#doc-wrapper , I am of the opinion this is outside the scope of cephci.

We predominately use images (VM and baremetal) to standup the requested platform. The [QCOW2 image| https://access.redhat.com/downloads/content/479/ver=/rhel---9/9.0/x86_64/product-software] is embedded with applications. Hence, we would need to build images that support this requirement.

IMO, we can use this issue for tracking support on availability of the image.

**Comment by sunilkumarn417** [comment]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/assembly_installing-a-rhel-8-system-with-fips-mode-enabled_security-hardening
