### ISSUE TITLE
Bug : ceph/utils.py - get_public_network method needs changes to findout public_network with multiple subnets

### ISSUE THREAD

**Issue by VasishtaShastry** [red-hat-storage/cephci#1496]
**Describe the bug**
get_public_network module retrieves subnet based on one node and if instances gets added with modes in multiple subnet, this makes it impossible to configure cluster using ceph-ansible as public_network config in all.yml needs to be added with comma separated value with all subnets.
 
https://github.com/red-hat-storage/cephci/blob/master/ceph/utils.py#L922-L935

**To Reproduce**
Run needs to have instances from multiple networks.

http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-4S6JPR/ceph_ansible_0.log

**Expected behavior**
get_public_network needs to be extended to gather subnets from all different VMs if subnet is different.

**Screenshots**

**Environment**
A concise description of your environment: RHEL version,
python version, operating system, command used etc.
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-4S6JPR/ceph_ansible_0.log

**Additional context**

**Comment by sunilkumarn417** [comment]
Need changes at,  https://github.com/red-hat-storage/cephci/blob/8be32512153cd9e81c1616e21ae429f3be5569e7/tests/ceph_installer/test_ansible.py#L33

**Comment by psathyan** [comment]
As the fix has been merged, closing this issue as fixed.
