### ISSUE TITLE
Archived logs should be available from IBM pipeline executions.

### ISSUE THREAD

**Issue by tintumathew10** [red-hat-storage/cephci#1560]
For the PSI runs we will get the magna link to validate the logs. Similar way it is good to have the archived logs available from IBM Pipeline executions.

Example: For validating startup logs user has to log into Report portal and download the logs from LogView.

**Comment by psathyan** [comment]
Thanks for raising this issue, yes we need to bring this back.

**Comment by sunilkumarn417** [comment]
We have compresed zip file for the test suite at report portal log view section. This is one of the test suite https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/all/5630/137630/log. Hence closing this issue.

**Comment by tintumathew10** [comment]
closing this issue as we have the logs available in report portal.
