### ISSUE TITLE
Sanity regression is getting executed on the same build two times.

### ISSUE THREAD

**Issue by tintumathew10** [red-hat-storage/cephci#1576]
On some of the RHCEPH-5.2 builds the sanity regressions are executed 2 times.

For ex: Search for "RHCEPH-5.2 - 16.2.8-63" in inbox. The sanity runs for all the tier got executed 2 times.

**Comment by psathyan** [comment]
Thanks for raising this issue... yes, we need to figure out a way in supporting this request. Earlier, we were aborting the previous runs.

**Comment by tintumathew10** [comment]
This issue is fixed.
