### ISSUE TITLE
interop 3.3 rbd failure

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#159]
3 RBD failures: in rhcs3.3 (7.9rc image)
# basic rbd tests

   - test:
      name: rbd cli image
      module: rbd_system.py
      config:
            test_name: cli/rbd_cli_image.py
            branch: master
      polarion-id: CEPH-83572722
      desc: CLI validation for image related commands

   - test:
      name: rbd cli snap_clone
      module: rbd_system.py
      config:
            test_name: cli/rbd_cli_snap_clone.py
            branch: master
      polarion-id: CEPH-83572725
      desc: CLI validation for snap and clone related commands

   - test:
      name: rbd cli misc
      module: rbd_system.py
      config:
            test_name: cli/rbd_cli_misc.py
            branch: master
      polarion-id: CEPH-83572724
      desc: CLI validation for miscellaneous rbd commands

**Comment by harishmunjulur** [comment]
tests are passing
