### ISSUE TITLE
Upgrade should have proper CLI args to accomodate the workaround required to upgrade to RHCS 5.1

### ISSUE THREAD

**Issue by manasagowri** [red-hat-storage/cephci#1596]
Workaround to upgrade to RHCS 5.1 to be applied in multihop upgrade. -  https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/5/4184

**Comment by manasagowri** [comment]
https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/5/3988/87491?launchesParams=page.page%3D1 

Launch where even non multihop upgrade has the same issue

**Comment by psathyan** [comment]
Not sure if this is a bug in the framework. The test module has to handle `custom-config`. Please let me know if you think otherwise.
