### ISSUE TITLE
interop rhcs4(rhel7,rhel8) rhcs3  cephfs failures

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#160]
* failing with py2 pip issue

**Comment by harishmunjulur** [comment]
https://github.com/red-hat-storage/cephci/pull/164

Waiting for complete successful logs

**Comment by yogesh-mane** [comment]
4.1-rhel-7 logs =http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1596957078656/
4.1-rhel-8 logs =http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1596949772303/
