### ISSUE TITLE
Once a node is defined as _admin node, keyring file should be copied into that node. Else cephadm-clients.yml playbook will fail

### ISSUE THREAD

**Issue by manasagowri** [red-hat-storage/cephci#1603]
If _admin node does not have keyring present cephadm-client.yml playbook will fail in below task

https://github.com/ceph/cephadm-ansible/blob/devel/cephadm-clients.yml#L88

Error log - https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/5/4028/89466/89521/log

**Comment by psathyan** [comment]
Could you please elaborate on what is expected here? cephadm applies `_admin` label and it is not in our control. We only retain the variable.
