### ISSUE TITLE
cross_platform_snaps (tier-2_cephfs_test-snapshot-clone suite) failure

### ISSUE THREAD

**Issue by yogesh-mane** [red-hat-storage/cephci#1611]
**Describe the bug**
cross_platform_snaps test is failing in tier-2_cephfs_test-snapshot-clone suite

**To Reproduce**
Run tier-2_cephfs_test-snapshot-clone suite

**Expected behavior**
All tests should pass

**Additional context**
report portal link - 
https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/all/4137/94473/94527/log?launchesParams=page.page%3D3

**Comment by hkadam134** [comment]
Fixed : https://github.com/red-hat-storage/cephci/pull/2031/files
