### ISSUE TITLE
Variable referenced before assignment in clone_threads

### ISSUE THREAD

**Issue by AmarnatReddy** [red-hat-storage/cephci#1624]
**Describe the bug**
Variable referenced before assignment in clone_threads
**rmclone_list** variable is defined in the last. we have **return** statement before that.
https://github.com/red-hat-storage/cephci/blob/84295911c28b803997d7e0132db31ec94a9d4e84/tests/cephfs/snapshot_clone/clone_threads.py#L158

**Add --force for the cleanup process as well**
**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
A concise description of your environment: RHEL version,
python version, operating system, command used etc.

**Additional context**

**Comment by hkadam134** [comment]
Fixed : https://github.com/red-hat-storage/cephci/pull/2031/files
