### ISSUE TITLE
Implement workaround for RHCS 5.1 upgrade. checkout options to fix HEALTH_ERR

### ISSUE THREAD

**Issue by manasagowri** [red-hat-storage/cephci#1633]
Upgrade test to RHCS 5.1 fails because it gives a health error - https://reportportal-rhcephqe.apps.ocp-c1.prod.psi.redhat.com/ui/#cephci/launches/all/3744/79165

    id:     1f513372-1c73-4690-8ec2-3d4e84f4822e
    health: HEALTH_ERR
            mons are allowing insecure global_id reclaim
            Upgrade: Using RHCS version with multisite regressions. Check "ceph health detail"

**Comment by psathyan** [comment]
Thanks for raising the issue. Could you elaborate on the issue, please?

**Comment by manasagowri** [comment]
Hi Pragadees,

So when we run an upgrade to RHCS 5.1, 
1. If we start from RHCS 4x - we need to pass -e qe_testing=true to rolling_update playbook
2. Also we need to set config - ceph config set mgr mgr/cephadm/yes_i_know true to bypass the HEALTH_ERR generated due to upgrade blocker.

This PR - https://github.com/red-hat-storage/cephci/pull/1677 should fix the issue.
