### ISSUE TITLE
Shrink OSD failed looking for the monitor which was removed in previous task shrink-mon

### ISSUE THREAD

**Issue by VasishtaShastry** [red-hat-storage/cephci#173]
I think we need to update playbook after shrinks
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1595954377478/shrink_osd_0.log
(Will update further)

**Comment by sunilkumarn417** [comment]
Shrink mon PR - https://github.com/red-hat-storage/cephci/pull/199
