### ISSUE TITLE
Add & Maintain the details about the GA'ed RHCS container details

### ISSUE THREAD

**Issue by pdhiran** [red-hat-storage/cephci#1738]
**Is your feature request related to a problem? Please describe.**
We need to maintain the details of all the GA'ed versions of RHCS in the `latest-rhceph-container-info` folder maintained for ceph deployments. Here : http://magna002.ceph.redhat.com/cephci-jenkins/latest-rhceph-container-info/

**Describe the solution you'd like**
Having all the details of all the versions, would help us quickly deploy a ceph cluster with required builds. Yes, we can explicitly specify images, but having a quick access to any build by specifying `--build 5.0z2 ` or ` --build 5.1z1 ` would save a lot of time.
This would help verify Customer scenarios.

We can add the builds with the info we already maintain the KCS article here : https://access.redhat.com/solutions/2045583

**Comment by psathyan** [comment]
Can we scope this request to RH lab only?

At present all the information is added to our recipe file and they can be installed by providing the below options
```
--rhbuild 5.1
--build z1-async1
--platform rhel-8
...
```
In case of upgrades, #1750 would address the gap.
