### ISSUE TITLE
config_roll_over - add_osd /add-mon - --limit needs to be replaced with add-osd / add-mon

### ISSUE THREAD

**Issue by VasishtaShastry** [red-hat-storage/cephci#177]
add-osd in luminous is failing saying  -
"msg": "The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'docker_exec_cmd'\n\nThe error appears to have been in '/usr/share/ceph-ansible/roles/ceph-mgr/tasks/common.yml': line 30, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n    - name: create ceph mgr keyring(s) on a mon node\n      ^ here\n"
}

As per the doc, we need to use add-osd.yml 
Ref - cephci-run-1595989707197

**Comment by Ameenasuhani** [comment]
https://github.com/red-hat-storage/cephci/pull/269
