### ISSUE TITLE
In RGW MS remove rgw_pullhost from primary setup all.yml

### ISSUE THREAD

**Issue by Ameenasuhani** [red-hat-storage/cephci#1854]
**Describe the bug**
In RGW MS rgw_pullhost is added both on primary and secondary but as per doc it has to be added only on secondary. Fix this all.yml

**Primary**
rgw_multisite: true
rgw_multisite_proto: http
**rgw_pullhost: 10.0.205.46**
rgw_realm: USA
rgw_zone: US_EAST

**Secondary**
rgw_multisite: true
rgw_multisite_proto: http
rgw_pull_port: 8080
rgw_pull_proto: http
**rgw_pullhost: 10.0.205.46**

**To Reproduce**
Run any multisite  suite which configures ms using ceph-ansible

**Additional context**
Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-K695SU/deploy_ceph_multisite_cluster_from_cdn_0.log

**Comment by mkasturi18** [comment]
PFA, Jira ticket https://issues.redhat.com/browse/RHCEPHQE-6456 for tracking the issue

**Comment by Ameenasuhani** [comment]
Log link: http://magna002.ceph.redhat.com/cephci-jenkins/archive/cephci-run-K695SU/
