### ISSUE TITLE
Upgrade fails when cdn and latest build point to same RHCS version

### ISSUE THREAD

**Issue by Ameenasuhani** [red-hat-storage/cephci#188]
Once a build is GA'ed the cdn and latest both build point to same RHCS version. So the script fails as "yum update" has "no packages to update".

Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1597133437286/

**Comment by sunilangadi2** [comment]
@Ameenasuhani 
I didn't hit this issue even though I have same version from pre and post upgrade
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1601523758341/result.html
also this PR https://github.com/red-hat-storage/cephci/pull/231 resolve this
Could you please let me know still are you able to reproduce this?

**Comment by Ameenasuhani** [comment]
The issue was an intermittent issue that seems to be resolved.
