### ISSUE TITLE
containerized ceph ansible task fails with error while enabling firewalld for RHEL-7.9-20200825.n.0-Server-x86_64 and RHEL-7.9-Server-x86_64-nightly-latest on 4.1 build

### ISSUE THREAD

**Issue by manasagowri** [red-hat-storage/cephci#198]
The cli used is
python run.py --rhbuild 4.1-rhel-7 --global-conf conf/nautilus/ansible/sanity-ceph-ansible.yaml --osp-cred osp/osp-cred-ci-2.yaml --inventory conf/inventory/rhel-7.9-server-x86_64.yaml --suite suites/nautilus/ansible/sanity_containerized_ceph_ansible.yaml --log-level info --store --report-portal --add-repo http://download.eng.bos.redhat.com/rhel-7/composes/auto/ceph-4.1-rhel-7/RHCEPH-4.1-RHEL-7-20200821.ci.1 --instances-name mgowri3

The error logs for the execution is present in the below path.
RHEL-7.9-20200825.n.0-Server-x86_64: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1598351360420/
RHEL-7.9-Server-x86_64-nightly-latest: 	http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1598353231300/

tried executing the systemctl enable firewalld command manually on the VM and got the same error.

**Comment by rakeshgm** [comment]
Can you do an RCA.
