### ISSUE TITLE
[RFE]: Support Config_roll_over to add multiple nodes at once

### ISSUE THREAD

**Issue by Ameenasuhani** [red-hat-storage/cephci#224]
**Description**: In the current framework only one node could be added per config_roll_over. Need support to add multiple node addition per config_roll_over.
https://github.com/red-hat-storage/cephci/blob/master/suites/luminous/ansible/sanity_ceph_ansible.yaml#L703

**Existing:**
add:
        - node:
             node-name: .*node15.*
             demon:
                  - mon

**Required:**
    add:
              - node:
                  node-name: .*node11.*
                  demon:
                      - client
                  node-name: .*node10.*
                  demon:
                      - client

**Comment by rakeshgm** [comment]
this could be generalised for other configs too
