### ISSUE TITLE
[RFE]: Support rbd-mirroring through ceph-ansible

### ISSUE THREAD

**Issue by Ameenasuhani** [red-hat-storage/cephci#227]
Description: In the existing framework scenario manual procedure for rbd-mirroring is used. Need support rbd-mirroring through ceph-ansible also.

Ref Links:
Doc bug: https://bugzilla.redhat.com/show_bug.cgi?id=1788094

**Comment by rakeshgm** [comment]
mirroring suite still has manual way of installing / configuring two sites 
https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/rbd/sanity_rbd_mirror.yaml 
ceph-ansible supports rbd mirroring.
