### ISSUE TITLE
prevent installing RHEL 8 builds on RHEL 7

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/cephci#250]
I accidentally ran `run.py` with `--rhbuild 4.2-rhel-8` and `--inventory conf/inventory/rhel-7.8-server-x86_64.yaml`, so cephci tried to install RHEL 8 builds on RHEL 7 nodes. It took me a while to figure out what I was doing wrong.

Maybe we should bail out early if we see that the user is 1) provisioning RHEL 7 VMs 2) specifying a "rhel-8" option to `--rhbuild`. We could print a helpful error explaining what they're doing wrong.

**Comment by sunilkumarn417** [comment]
I Agree on this, we should find out a way to bail out before creating instances.

Possible solutions, on Assuming we have distribution name and version in Compose Build URL
1) we can include distro-version for all entries for `--rhbuild`, where distro version could be parsed and compared with compose build URL.
for eg., `--rhbuild 3.3-rhel-7` --> `distro = rhel-7` --> `"rhel-7" in build URL path`.
2) Or by adding a CLI parameter to consider OS distribution version.

**Comment by ktdreyer** [comment]
What if we maintained a `conf/inventory/rhel-7-server-x86_64.yaml` (so, no minor version number), and we defaulted to using that one?

Then if you want to test an *older* RHEL minor release, you can do that by setting the `--inventory` option. Otherwise the default behavior would be to always use the latest RHEL minor release.
