### ISSUE TITLE
sanity_ceph_ansible.yaml fails with small global-conf

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/cephci#251]
I accidentally ran `run.py` with `--global-conf conf/nautilus/ansible/sanity-ceph-ansible-small.yaml` using the main (non-small) `--suite suites/nautilus/ansible/sanity_ceph_ansible.yaml`. This failed a couple of tests.

It took me a while to figure out what I was doing wrong.

Do we expect `sanity-ceph-ansible-small.yaml` to pass with the main `sanity_ceph_ansible.yaml` suite?

If not, how can we make this user experience better so users don't run the wrong thing?

**Comment by rakeshgm** [comment]
I see your point. Yes there are times when we end up running wrong yaml. but I dont think there is any code to combine more than one yaml here.
