### ISSUE TITLE
Bug: [Bare-metal] Add support of deploying OSD on defined disks

### ISSUE THREAD

**Issue by udaysk23** [red-hat-storage/cephci#2650]
**Describe the bug**
Add support of deploying OSD on defined disks in bare-metal deployment.

In current flow, the parameter `all-available-devices = true` is considering all available disks present on node. There is no way of defining specific disks as part of OSD.

**Comment by AmarnatReddy** [comment]
Its on all CephCI Runs @udaysk23.
If that is fixed it should work for baremetal as well

**Comment by mkasturi18** [comment]
@vamahaja , can we take this up in Q3

**Comment by MohitBis** [comment]
Hi All,

Using "pos_args" parameter we can mention specific node and disk, Please refer below exmple

  - test:
      name: Add osd
      desc: Add osd on second node
      module: test_daemon.py
      config:
        command: add
        service: osd
        **pos_args:**
          - "node3"
          - **"/dev/vdb"**
          - "/dev/vdc"
          - "/dev/vdd"
      destroy-cluster: false
      abort-on-fail: true
