### ISSUE TITLE
merge mita CephVMNode "driver" with "driver_v2"

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/cephci#289]
We have `self.driver` and `self.driver_v2` in [mita/openstack.py](https://github.com/red-hat-storage/cephci/blob/master/mita/openstack.py). The internal rhos-d environment is running RHOSP 16 now, so the server environment is fairly modern. It would be great to use one single driver everywhere, so we can simplify the code.

Here are the `CephVMNode` methods that are still using the older `self.driver`:

- [x] `get_private_ip()`
- [x] `get_volume()`
- [x] `destroy_node()`
- [x] `destroy_volume()`
- [x] `destroy_node`
- [x] `attach_floating_ip()`

**Comment by psathyan** [comment]
As part of the first step, moving the resources to use `driver_v2`

- #295 
- #296 
- #297 
- #298 
- #299
