### ISSUE TITLE
s3_tests failing

### ISSUE THREAD

**Issue by rakeshgm** [red-hat-storage/cephci#292]
Some of the `s3_tests` in [rgw_suite](https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/rgw/sanity_rgw.yaml#L659) are failing. We need to triage which are the tests that are failing and why. These tests are present in an external [repo](https://github.com/ceph/s3-tests). In cephci we just have the [integration code](https://github.com/red-hat-storage/cephci/blob/master/tests/rgw/test_s3.py ) and not the actual tests.

**Comment by psathyan** [comment]
Initial test logs are available @ [link](http://magna002.ceph.redhat.com/ceph-qe-logs/psathyan/s3_tests/1/)

**Analysis**
- TBC

**Comment by psathyan** [comment]
Changes required
- [ ] Modify the execution command of `s3_tests` to include the option `-a '!fails_on_rgw'`

**Comment by psathyan** [comment]
Test execution with `-a '!fails_on_rgw` results are

| Number of Tests | Passed | Skipped | Failed | Error |
| ---------------------- | ---------- | ----------- | -------- | ------- |
| 555 | 431 | 84 | 11 | 29 |

**Comment by psathyan** [comment]
Setting the parameter `rgw_crypt_require_ssl = False` in the conf file allows us to pass `SSE-C` tests however the tests related to `KMS` still fail.

**Comment by psathyan** [comment]
#318 provides us a baseline to build upon. It closes the tasks related to `changes required`

**Comment by psathyan** [comment]
With pacific the results are
```
Ran 460 tests in 1039.209s

FAILED (failures=17)
```

**Comment by psathyan** [comment]
The following support have been added to increase the s3test coverage

- support SSL endpoint
- support vault integration

This PR #705 adds support for executing `encryption` tests

**Comment by psathyan** [comment]
As of Jan 8, 2022 - RHCS 5.0 

```
virtualenv/bin/nosetests -v -a '!fails_on_rgw,!fails_strict_rfc2616,!encryption,!test_of_sts,!s3select,!user-policy,!webidentity_test' s3tests_boto3 on 10.245.7.45
2022-01-08 07:43:52,935 - ceph.ceph - INFO - Command completed successfull

----------------------------------------------------------------------
Ran 460 tests in 741.394s

OK

```

**Comment by mkasturi18** [comment]
PFA, Jira ticket https://issues.redhat.com/browse/RHCEPHQE-6457 for investigating on the issue

**Comment by TejasC88** [comment]
Closing this issue as we are Green on Pacific and Red on Quincy due to differences between upstream and downstream code.
