### ISSUE TITLE
RFE on IBM : Container info params needs to be handled implicitly in cephci framework instead of user providing it.

### ISSUE THREAD

**Issue by sumabai** [red-hat-storage/cephci#2943]
**Is your feature request related to a problem? Please describe.**
Currently, for jenkins cephci execution on IBM build the mandatory params list looks as below,

------------------------------------------
python3 run.py --osp-cred osp/osp-cred-ci-2.yaml --rhbuild 7.0 --platform rhel-9 --instances-name sumar_cephfs --global-conf conf/pacific/cephfs/tier-0_fs.yaml --suite suites/pacific/cephfs/tier-0_fs.yaml --inventory conf/inventory/rhel-9-latest.yaml  --log-level DEBUG --build latest --custom-config ibm-build=True --custom-config node_exporter_image=cp.stg.icr.io/cp/ibm-ceph/prometheus-node-exporter:v4.12.0-202305262042.p0.gaf2f49c.assembly.stream --custom-config prometheus_image=cp.stg.icr.io/cp/ibm-ceph/prometheus-alertmanager:v4.12.0-202305262042.p0.g86b1835.assembly.stream --custom-config grafana_image=cp.stg.icr.io/cp/ibm-ceph/grafana-rhel9:9.4.7-1 --custom-config haproxy_image=cp.stg.icr.io/cp/ibm-ceph/haproxy-rhel9:2.4.17-4 --custom-config keepalived_image=cp.stg.icr.io/cp/ibm-ceph/keepalived-rhel9:2.2.4-3 --custom-config snmp_gateway_image=cp.stg.icr.io/cp/ibm-ceph/snmp-notifier-rhel9:1.2.1-36 --rhs-ceph-repo https://public.dhe.ibm.com/ibmdl/export/pub/storage/ceph/testing/IBM-CEPH-7.0-20230911.ci.0/IBM-CEPH-7.0-20230911.ci.0-rhel9.repo --docker-registry cp.stg.icr.io --docker-image cp/ibm-ceph/ceph-7-rhel9 --docker-tag 7-1
------------------------------------------

This is an inconvenience to user to manually fetch latest container builds for all ceph components like node_exporter, grafana, ha_proxy, snpm_gateway and others. 

**Describe the solution you'd like**
Cephci framework needs to update latest container builds for above ceph components in metadata file as "latest-rhceph-container-info" and needs to fetch param values for run.py from this file.

**Describe alternatives you've considered**

**Additional context**

**Comment by neha-gangadhar** [comment]
@vamahaja @tintumathew10 Anyone is tracking the issue logged here?

**Comment by vamahaja** [comment]
@neha-gangadhar we have working on to provide similar feature in CI/CD jobs. We can close this one as CI/CD is tracked in JIRA.

**Comment by neha-gangadhar** [comment]
@vamahaja Can you please add the JIRA details here so that we can close it.
