### ISSUE TITLE
Ceph-medic support missing

### ISSUE THREAD

**Issue by Ameenasuhani** [red-hat-storage/cephci#304]
Description: Ceph-medic support missing

The ceph-medic utility detects common issues with a Ceph Storage Cluster that prevents it from functioning properly.

Ref doc: https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/4/html/troubleshooting_guide/installing-and-using-ceph-medic-to-diagnose-a-ceph-storage-cluster

**Comment by VasishtaShastry** [comment]
Closing this issue as ceph-medic is deprecated from 4.x
Please let us know if there are any concerns
