### ISSUE TITLE
RADOS: Enabling encryption on wire feature test execution  failed  

### ISSUE THREAD

**Issue by SrinivasaBharath** [red-hat-storage/cephci#322]
Enabling encryption on wire feature MSGR Version2 test case failed in 5.0.
Error Snippet:

  021-01-22 05:17:46,663 - ceph.ceph - INFO - Running command ceph mon enable-msgr2 on 10.0.102.71
2021-01-22 05:17:46,685 - ceph.ceph - ERROR - Error during cmd 127, timeout 120
2021-01-22 05:17:46,686 - __main__ - ERROR - Traceback (most recent call last):
  File "run.py", line 611, in run
    ceph_cluster_dict=ceph_cluster_dict, clients=clients)
  File "/home/skanta/cephadm-cephci/cephci/tests/rados/test_83573482.py", line 51, in run
    out, err = exec_cmd_status(mon_nodes[0], command=ENABLE_MSGR2, sudo=True)
  File "/home/skanta/cephadm-cephci/cephci/tests/rados/test_83573482.py", line 22, in exec_cmd_status
    out, err = ceph_node.exec_command(sudo=sudo, cmd=command)
  File "/home/skanta/cephadm-cephci/cephci/ceph/ceph.py", line 1192, in exec_command
    raise CommandFailed(kw['cmd'] + " Error:  " + str(stderr.read().decode()) + ' ' + str(self.ip_address))
ceph.ceph.CommandFailed: ceph mon enable-msgr2 Error:  bash: ceph: command not found
 10.0.102.71

**Comment by rakeshgm** [comment]
@SrinivasaBharath can take another look at this ?

**Comment by pdhiran** [comment]
Hi @SrinivasaBharath ,

Since the commands are being run on 5.0 env, there are no ceph* packages present on the host node. looking at the command run,
``` out, err = ceph_node.exec_command(sudo=sudo, cmd=command)

ceph.ceph.CommandFailed: ceph mon enable-msgr2 Error: bash: ceph: command not found
10.0.102.71 ```

You are using ` exec_command ` call, which by default runs on host, and it is appropriately returning the error stating that ` ceph ` command not found. 

We need to run commands via ` cephadm shell ` for these commands to work. Also, msgrV2 is enabled by from 4.x onwards. Same can be verified via ` ceph mon dump ` or by ` netstat command `

``` # netstat -tulpn | grep 3300
tcp        0      0 10.8.128.45:3300        0.0.0.0:*               LISTEN      2224292/ceph-mon
```
or 
``` # ceph mon dump
epoch 13
fsid 0a68a516-38dd-11ec-8143-002590fbc342
last_changed 2021-11-19T05:03:23.584614+0000
created 2021-10-29T17:25:04.344031+0000
min_mon_release 16 (pacific)
election_strategy: 3
stretch_mode_enabled 1
tiebreaker_mon magna047
disallowed_leaders magna047
0: [v2:10.8.128.45:3300/0,v1:10.8.128.45:6789/0] mon.magna045; crush_location {datacenter=site-A}
1: [v2:10.8.128.46:3300/0,v1:10.8.128.46:6789/0] mon.magna046; crush_location {datacenter=site-B}
2: [v2:10.8.128.47:3300/0,v1:10.8.128.47:6789/0] mon.magna047; crush_location {datacenter=arbiter}
dumped monmap epoch 13
```

I think we can close the issue. Let me know your thoughts.

**Comment by pdhiran** [comment]
Discussed issue, closing.
