### ISSUE TITLE
[RFE]: Add support for RGW NFS in CI

### ISSUE THREAD

**Issue by udaysk23** [red-hat-storage/cephci#329]
we need to adda broker script in ceph-ci like sanity_rgw.py to run external tests from ceph-qe-scripts

**Comment by mkasturi18** [comment]
The nfs-rgw (nfs-ganesha) tests are automated in nautilus
https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/rgw/tier-2_rgw_ganesha.yaml 
https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/rgw/tier-2_rgw_test-4x-ganesha-upgrade-to-latest.yaml
https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/rgw/tier-3_rgw_ganesha.yaml

Closing this issue
