### ISSUE TITLE
RBD: Mirroring tests are failing due to CLI changes

### ISSUE THREAD

**Issue by harishmunjulur** [red-hat-storage/cephci#330]
Currently all mirroring tests on 4.2 are failing due to changes in CLI.

**Comment by harishmunjulur** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1910280

**Comment by Gopi-Patta** [comment]
Cephci is failing and filed a ticket https://redhat.service-now.com/help?id=rh_ticket&table=incident&sys_id=0a3fe5e41bc26050c553fe28dc4bcbf7
will resume cephci once the ticket gets resolved.

**Comment by rakeshgm** [comment]
CI is running fine now. http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1612249933148/result.html

**Comment by Gopi-Patta** [comment]
Issue is still exists.

**Comment by Gopi-Patta** [comment]
Test cases are passing now. 
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-IHV079/
