### ISSUE TITLE
RBD [RFE] - snapshot based rbd mirroring 

### ISSUE THREAD

**Issue by harishmunjulur** [red-hat-storage/cephci#334]

**Comment by VasishtaShastry** [comment]
Snapshot based mirroring seems to be there already -
https://github.com/red-hat-storage/cephci/blob/master/tests/rbd_mirror/rbd_mirror_utils.py#L538-L550
https://github.com/red-hat-storage/cephci/blob/master/tests/rbd_mirror/test_rbd_mirror_image.py#L67-L77
cc @Gopi-Patta

**Comment by VasishtaShastry** [comment]
Closing this issue as RFE title has bene implemented already
