### ISSUE TITLE
results.html shows incorrect ceph version when using hotfix repo

### ISSUE THREAD

**Issue by rakeshgm** [red-hat-storage/cephci#340]
This [Test](http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1612772262124/result.html) shows the version as  `14.2.11-117.el8cp` . But the test was used with `--hotfix-repo` cli option which has `14.2.11-95.0.hotfix.bz1901973.el8c` as the ceph version.  Results.html should have `14.2.11-95.0.hotfix.bz1901973.el8c` as ceph version in the report

Attaching reference [logs](http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1612772262124/result.html)  and [hotfix-repo file](http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/hotfixes/bz1901973-el8/bz1901973-el8.repo) which was used in this test.

**Comment by pdhiran** [comment]
We always provide the hotfix repo as : ` --hotfix-repo http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/hotfixes/bz1856100/bz1856100.repo ` path right? 

Here we can check all the ceph packages are present via the ` baseurl= ` value.

eg : We can fetch the ceph versions for the above hox-fix repo from baseurl, i.e : http://download.eng.bos.redhat.com/rcm-guest/ceph-drops/hotfixes/bz1856100/repo/

is the approach correct? @rakeshgm

**Comment by rakeshgm** [comment]
can be planned in ci-v2
