### ISSUE TITLE
prometheus daemon does not come up with cephadm_deploy suite

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/cephci#342]
When I run [`suites/pacific/cephadm/cephadm_deploy.yaml`](https://github.com/red-hat-storage/cephci/blob/c86c671ed70aa944a48d01012156504f203dab5a/suites/pacific/cephadm/cephadm_deploy.yaml) , cephci loops waiting for prometheus to come up.

```
2021-02-08 15:58:34,307 - ceph.ceph_admin - INFO - 0/1 prometheus daemon(s) up... Retries: 165.0
2021-02-08 15:58:41,544 - ceph.ceph_admin - INFO - 0/1 prometheus daemon(s) up... Retries: 164.0
2021-02-08 15:58:48,511 - ceph.ceph_admin - INFO - 0/1 prometheus daemon(s) up... Retries: 163.0
```

Is this because we run cephadm with `--skip-monitoring-stack` in  [`ceph/ceph_admin/bootstrap_mixin.py`](https://github.com/red-hat-storage/cephci/blob/c86c671ed70aa944a48d01012156504f203dab5a/ceph/ceph_admin/bootstrap_mixin.py)?

**Comment by sunilkumarn417** [comment]
Currently loop exists to check particular service process(es) status and waits out for successful deployment till timeout. 
`  --skip-monitoring-stack ` option skips default creation of prometheus and other monitoring services at the time of bootstrap.
https://docs.ceph.com/en/latest/cephadm/monitoring/#monitoring-stack-with-cephadm

applying prometheus service has worked for us recently, after using `skip-monitoring-stack` at bootstrap.
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1612851035893/Apply_Prometheus_Service_0.log

**Comment by ktdreyer** [comment]
I'm sorry I'm not following. Is there some change you've made to `cephadm_deploy.yaml` or one of the cephadm-related files?

**Comment by ktdreyer** [comment]
Sunil and I chatted further about this. Sunil linked to https://github.com/red-hat-storage/cephci/blob/ddc3cb5fde5400b2ada2bea13ceb32b1129d526d/ceph/ceph_admin/__init__.py#L260-L288

Here is my full `run.py` invocation:

```
venv/bin/python run.py \
  --rhbuild 5.0 \
  --global-conf conf/pacific/cephadm/sanity-cephadm.yaml \
  --osp-cred ~/osp-cred-kdreyer.yaml \
  --inventory conf/inventory/rhel-8.3-server-x86_64.yaml \
  --suite suites/pacific/cephadm/cephadm.yaml \
  --log-level info \
  --ignore-latest-container \
  --insecure-registry \
  --docker-registry registry-proxy.engineering.redhat.com \
  --docker-image rh-osbs/rhceph \
  --docker-tag ${image_tag}
```

**Comment by ktdreyer** [comment]
I tried `run.py` with both suites:

* `--suite suites/pacific/cephadm/cephadm.yaml` - does not bring up prometheus.
* `--suite suites/pacific/cephadm/cephadm_deploy.yaml` - does not bring up prometheus.

I'm using `--docker-tag ceph-5.0-rhel-8-containers-candidate-17877-20210129182254`.

**Comment by ktdreyer** [comment]
Ok, I see the problem in the log now.

registry.redhat.io/openshift4/ose-prometheus:v4.6...
stat: stderr   unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
stat: stderr Error: unable to pull registry.redhat.io/openshift4/ose-prometheus:v4.6:

I did not have `cdn_credentials` set in `~/.cephci.yaml`.

**Comment by ktdreyer** [comment]
Ok, setting `cdn_credentials` allows cephci to deploy prometheus. I've added some help text in https://github.com/red-hat-storage/cephci/pull/346
