### ISSUE TITLE
stop installing redhat-lsb on RHEL

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/cephci#357]
With commit bad8f5ebe7b909a355ee38bbd42083919d7acfa5, we install `redhat-lsb` on every node. This installs many packages, like Perl and gtk2.

_What uses redhat-lsb?_

We instruct Ubuntu users to install `lsb-release` in order to run the `lsb_release` command. Users run this command when [enabling Apt repos on Ubuntu](https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html/installation_guide_for_ubuntu/requirements-for-installing-rhcs#enabling-the-red-hat-ceph-storage-repositories).

**_It appears that nothing in cephci uses redhat-lsb on RHEL._**

_Why do we install redhat-lsb?_

I'm wondering if the author only added it because he added lsb-release on Ubuntu the day before (commit 82d58826441ba0d59f26d2e5426d3f544fc8daae).

_How much time/space does redhat-lsb require?_

As one example, `yum remove perl-devel` on RHEL 8 removes 240 unneeded packages, 226 MB.

RHEL 8 has a `redhat-lsb-core` package that does not install as many dependencies, but given the fact that we do not appear to use any lsb-related features on RHEL at all, we could probably remove `redhat-lsb` altogether.

_Summary_

If we can stop installing redhat-lsb on every test node, it will shave time off every test run.

**Comment by vasukulkarni** [comment]
I believe some of the workunits need it thats why you might not find it in this repo, have to run full test to figure out if its still required..

**Comment by ktdreyer** [comment]
Where are the workunits?

**Comment by ktdreyer** [comment]
Can we at least move the `redhat-lsb` package install to `tests/misc_env/test_workunit.py` instead of `tests/install_prereq.py` ? Then we would not have to install it all the time. For example, small cephadm sanity tests. do not use workunits.
