### ISSUE TITLE
set up cephuser account with cloud-init

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/cephci#358]
It's not clear to me why we change each node's `cephuser` account password during the test runs. We could do this immediately in each cloud-init config instead of doing it one-by-one over SSH during the tests. This would save time and make the logs smaller and easier to read.

**Comment by vasukulkarni** [comment]
If you check the cloud-init it is setup as 'pass123', but some for some of the early distro's it never worked reliably , thats why it is setup later, also the task of vm setup is parallel

**Comment by ktdreyer** [comment]
Thanks Vasu. Do you have any more information about that bug?

I'm wondering if this cloud-init limitation still applies to any distros that we support today:

RH Ceph Storage 3 on RHEL 7.latest + Ubuntu Xenial
RH Ceph Storage 4 on RHEL 7.latest + RHEL 8.latest
RH Ceph Storage 5 on RHEL 8.latest

For example, RHEL 7.4 introduced cloud-init as [cloud-init-0.7.9-9.el7 four years ago](https://access.redhat.com/errata/RHEA-2017:2275), and now it has [cloud-init-19.4-7.el7_9.3](https://access.redhat.com/errata/RHBA-2020:5446).

**Comment by vasukulkarni** [comment]
Hi Ken, I actually dont have much information about the old bug but I think we can try now with latest cloud-init as there is a major difference now and if it works for the lowest supported distro probably it should work for higher up.
