### ISSUE TITLE
Some of the runcmds commands part of cloud-init fail

### ISSUE THREAD

**Issue by psathyan** [red-hat-storage/cephci#361]
A snippet of the cloud-init-output.log
```
Cloud-init v. 18.5 running 'modules:config' at Tue, 16 Feb 2021 10:47:07 +0000. Up 163.25 seconds.
Main config did not have a skip_missing_names_on_install attr. before setopt
Main config did not have a skip_missing_names_on_install attr. before setopt
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
Failed to stop firewalld.service: Unit firewalld.service not loaded.
Cache was expired
```

The image used for creating the instances don't have a repo configured nor does it have `firewalld` service.

**Comment by ktdreyer** [comment]
I think we could move the RHEL Yum repository settings into the configurations that we pass to cloud-init.

**Comment by ktdreyer** [comment]
> I think we could move the RHEL Yum repository settings into the configurations that we pass to cloud-init.

Oh, we use `subscription-manager` to enable the RHEL repos, so it's not simple to use the built-in cloud-init modules. Given the complexity of what we are doing in `tests/install_prereq.py`, let's move it all into that location.

**Comment by ktdreyer** [comment]
By the way, I tested cloud-init's `rh_subscription` module this week. It's ok for the basic case, but it does not support the equivalent of `subscription-manager repos --disable='*'`, https://bugs.launchpad.net/cloud-init/+bug/1915942 , so there is still more to be done there, and RHEL 7 will probably never see a fix for that at this point in RHEL 7's lifecycle.

**Comment by rakeshgm** [comment]
are we still seeing this issue now a days. ?

**Comment by psathyan** [comment]
yes, the issue still persists still we identify a way to include subscription
