### ISSUE TITLE
Install failed during ceph-ci run due to mis-match in compose [New build published in middle of ceph install]

### ISSUE THREAD

**Issue by veera-raghava-reddy** [red-hat-storage/cephci#373]
Ceph install failed with one of the nodes - 'Failed to download packages: Cannot download Packages/libcephfs2-14.2.11-122.el8cp.x86_64.rpm:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1613584723122/ceph_ansible_3.log

Reason while installing ceph version 14.2.11-122, new build was published and previous version of rpms were not available.

Also some nodes got installed with 14.2.11-123.

Need to handle build used for CI runs.

**Comment by sunilkumarn417** [comment]
Probably, this is due to usage of latest compose URL`composes/auto/ceph-5.0-rhel-8/latest-RHCEPH-5-RHEL-8/` rather than particular build URL `composes/auto/ceph-5.0-rhel-8/RHCEPH-5.0-RHEL-8-20210216.ci.1/`.

**Comment by ktdreyer** [comment]
I have been meaning to use `compose-write-repo-file` from https://pagure.io/compose-utils to generate a standard .repo file for every compose after release engineering generates it. Maybe that would help here if each compose's .repo file had an identical name.

**Comment by rakeshgm** [comment]
@psathyan we are not seeing this issue anymore right with the pipeline implementation?

**Comment by psathyan** [comment]
Can we keep this open till the next version of Pipeline is completed?
