### ISSUE TITLE
[RFE]: Enhance the CLI required to trigger runs

### ISSUE THREAD

**Issue by Ameenasuhani** [red-hat-storage/cephci#382]
Alter the cli required to intialise a run for the user to avoid/reduce error

**Comment by rakeshgm** [comment]
can please you add more information here

**Comment by Ameenasuhani** [comment]
The cli required to initialise a run is too long and introduces human error so possibly expecting to somehow alter it to ease the triggering the run.

**Comment by Ameenasuhani** [comment]
Fixed
