### ISSUE TITLE
Calling setup_packages in prereq affecting upgrade tests suites

### ISSUE THREAD

**Issue by VasishtaShastry** [red-hat-storage/cephci#406]
Calling setup_packages in prereq affecting upgrade test suites by enabling latest repos instead of required (n-1 version)
https://github.com/red-hat-storage/cephci/blob/c95c0034ad18bfbd5a6668fa5a3c1c485d05b1e8/tests/misc_env/install_prereq.py#L63-L65

Before code was included to call the func in prereq- http://magna002.ceph.redhat.com/ceph-qe-logs/vasishta/for_BZ1935554/
After rebasing to master (with setup func in prepreq - http://magna002.ceph.redhat.com/ceph-qe-logs/vasishta/tmp/
After commenting out - http://magna002.ceph.redhat.com/ceph-qe-logs/vasishta/to_test_1935554/

**Comment by VasishtaShastry** [comment]
ping @andrewschoen

**Comment by andrewschoen** [comment]
@VasishtaShastry I just created #409 to address this.
