### ISSUE TITLE
Add support of parallel execution in cephci

### ISSUE THREAD

**Issue by udaysk23** [red-hat-storage/cephci#414]
Add support of parallel execution in cephci

**Comment by veera-raghava-reddy** [comment]
@udaysk23 Elaborate on the use-case. What needs to be run in parallel. For example multiple tests on the same cluster?

**Comment by sunilkumarn417** [comment]
@udaysk23 , can you make use of parallel module defined in CEPH-CI as  below.
https://github.com/red-hat-storage/cephci/blob/master/tests/misc_env/install_prereq.py#L45
Hope this helps and  please close the issue if it solves the issue.

**Comment by rakeshgm** [comment]
we have parallel task in ceph-ci.
