### ISSUE TITLE
SELinux Package is not getting installed when tried with RHEL7.7

### ISSUE THREAD

**Issue by AmarnatReddy** [red-hat-storage/cephci#415]
SElinux installation is Failing on Monitor nodes when tried running with RHEL 7.7

Error Message : "Error: Package: 2:ceph-selinux-12.2.12-137.el7cp.x86_64 (ceph-MON)\n           Requires: selinux-policy-base >= 3.13.1-268

Please find the log files:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1615357180267

**Comment by ktdreyer** [comment]
We don't have ceph-selinux packages that are compatible with RHEL 7.7 EUS at this point. We're still discussing what we want to formally support here.

**Comment by rakeshgm** [comment]
rhel-7.7 EUS packs ceph-selinux packages right @ktdreyer . ?
