### ISSUE TITLE
Install ceph-common on all the ceph-nodes in cluster

### ISSUE THREAD

**Issue by AmarnatReddy** [red-hat-storage/cephci#4190]
**Describe the bug**
Install ceph-common on all the ceph-nodes in cluster

This is to help sosreport to collect the ceph commands. 
with out ceph-common sosreport will not be able to collect following commands

```
[root@ceph1-amk-mirror-9tdhoy-node1-installer sos_commands]# ls -lrt | grep ceph 
drwx------. 2 root root   21 Oct 15 04:16 ceph_common
drwx------. 2 root root 8192 Oct 15 04:16 ceph_mds
drwx------. 3 root root 4096 Oct 15 04:17 ceph_mgr
drwx------. 3 root root 4096 Oct 15 04:18 ceph_mon
[root@ceph1-amk-mirror-9tdhoy-node1-installer sos_commands]# ls -lrt ceph_common/
total 4
-rw-r--r--. 1 root root 86 Oct 15 04:10 ceph_-v
[root@ceph1-amk-mirror-9tdhoy-node1-installer ceph_common]# cat ceph_-v 
timeout: failed to run command ‘ceph’: No such file or directory

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**
A concise description of your environment: RHEL version,
python version, operating system, command used etc.

**Additional context**

**Comment by psathyan** [comment]
@sunilkumarn417 there was some reason why we were not doing installing `ceph-common` earlier. Would you be able to add your thoughts here?

**Comment by sunilkumarn417** [comment]
`ceph-common` provides different rpm and utility tools to manage ceph for many scenarios and Now we have cephadm orchestration tool which manages most of the operations and also provide these utilities.

So its better to use `ceph-common` only when it is needed(unless it is required) and encourage users to use more cephadm operations.

**Comment by AmarnatReddy** [comment]
https://github.com/red-hat-storage/cephci/pull/4192
