### ISSUE TITLE
Standardize on python string format

### ISSUE THREAD

**Issue by psathyan** [red-hat-storage/cephci#447]
## Issue
At present, there are various implementation of python strings applied in our code. For example

```
Example 1
   log.info(f"The value of foo is {foo}")

Example 2
    log.info("The value of foo is {}".format(foo))

Example 3
    log.info("The value of foo is {foo}".format(foo=foo))

Example 4
    log.info("The value of foo is %s" % foo)

Example 5
    log.info("The value of foo is %s", foo)
```

## Proposal
As a guideline, we could follow the below

1. Use `String Interpolation/ f-strings` as the first choice [1]
        `msg = f"Hello !!! {name}"`
2. For logging, as a first choice use `%-format strings`. [2]. For example
         `log.info("Hello !!!, %s", name)`

### References
[1] https://realpython.com/python-string-formatting/
[2] https://docs.python.org/3/howto/logging-cookbook.html#use-of-alternative-formatting-styles

**Comment by rakeshgm** [comment]
I would propose to use of format strings everywhere to keep things simple.

**Comment by pdhiran** [comment]
I suggest that we can go with [1] for all the strings. That will keep things uniform and easy for anyone.

**Comment by rakeshgm** [comment]
example: `print(f"my name is {rakesh}"`

**Comment by ktdreyer** [comment]
Agreed we should use f-strings everywhere.

**Comment by rakeshgm** [comment]
i think this is documented as coding guidelines.
