### ISSUE TITLE
Ceph health check fails with error - ERROR - 'str' object has no attribute 'read'

### ISSUE THREAD

**Issue by manasagowri** [red-hat-storage/cephci#468]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1619152243856/check-ceph-health_1.log

While running upgrade_containerized on a rhel-8 cluster for 4.2z1 RC, the ceph health check failed.

2021-04-23 01:47:52,747 - exec - ERROR - 'str' object has no attribute 'read'

**Comment by psathyan** [comment]
`long_running=True` returns a str leading to a failure
