### ISSUE TITLE
Error message when no of volumes and their sizes are not mentioned for OSD nodes in conf file lacks clarity

### ISSUE THREAD

**Issue by manasagowri** [red-hat-storage/cephci#484]
When no. of  volumes and size parameter is not mentioned for an OSD node, the error message provided lacks clarity.

2021-04-28 05:15:15,724 - ceph.utils - INFO - Done creating nodes
2021-04-28 05:15:15,727 - __main__ - ERROR - Insufficient of free volumes

**Comment by manasagowri** [comment]
https://github.com/red-hat-storage/cephci/pull/488

PR raised to fix this issue.

**Comment by sunilkumarn417** [comment]
This PR fixes the issue - https://github.com/red-hat-storage/cephci/pull/488
