### ISSUE TITLE
Update Tier0,1 test run OS template to RHEL 8.4

### ISSUE THREAD

**Issue by veera-raghava-reddy** [red-hat-storage/cephci#521]

**Comment by psathyan** [comment]
- [ ] RHCS 5.0 Tier 0 completer
- [ ] RHCS 5.0 Tier 1 completer
- [ ] RHCS 4.3 Tier 0 completer

Right now 100% of the Tier-0 jobs of RHCS 5.0 have been moved to RHEL 8.4...

**Comment by psathyan** [comment]
This issue has been fixed in a series of PR raised by @ckulal... closing the issue. Please feel free to re-open if the requirement is not meet.
