### ISSUE TITLE
Enhancement : Standard script to collect all the logs from ceph cluster

### ISSUE THREAD

**Issue by AmarnatReddy** [red-hat-storage/cephci#562]
Enhancement: Standard script to collect all the logs from ceph cluster

Can we have a script to collect the logs from the ceph cluster in zip format.
This helps to attach logs to the Bzs without missing anything.

**Comment by anrao19** [comment]
pr: Through Install node collect logs from other host
https://github.com/red-hat-storage/cephci/pull/700
