### ISSUE TITLE
nfs cluster deployment failing in rhcs4.0

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#66]
[](https://bugzilla.redhat.com/show_bug.cgi?id=1786110)

Workaround: set selinux to permissive

**Comment by XDsubhash** [comment]
[https://bugzilla.redhat.com/show_bug.cgi?id=1786110](url)

**Comment by XDsubhash** [comment]
[Fixed](https://bugzilla.redhat.com/show_bug.cgi?id=1786110)

**Comment by XDsubhash** [comment]
[regression](https://bugzilla.redhat.com/show_bug.cgi?id=1786110)

**Comment by rakeshgm** [comment]
@XDsubhash  is this on RHCS Nautilus?

**Comment by XDsubhash** [comment]
yes 4.0-rhel-8 deploys shud hit this issue

**Comment by XDsubhash** [comment]
fixed in 4.1-rhel-8 (rhel8.1)

**Comment by XDsubhash** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1829804 cant uncomment interop suite nfs deploy until 4.1GAed with this fix
