### ISSUE TITLE
[Jenkin]:Publish result not working in tier1 wrapper when triggered by timer

### ISSUE THREAD

**Issue by ckulal** [red-hat-storage/cephci#709]
When triggered by timer:
parameter (CI_MESSAGE) empty: at that time it fails
https://ceph-downstream-jenkins-csb-storage.apps.ocp4.prod.psi.redhat.com/view/RHCS%204%20QE/job/rhceph-4-tier-1-wrapper/31/

when triggered manually py providing parameter(CI_MESSAGE): PASS
https://ceph-downstream-jenkins-csb-storage.apps.ocp4.prod.psi.redhat.com/view/RHCS%204%20QE/job/rhceph-4-tier-1-wrapper/32/

**Comment by rakeshgm** [comment]
issue is fixed. PR is tagged above.
