### ISSUE TITLE
Fix issues in VM cleanup and floating IPs availability

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#80]
* cleanup script might not be deleting the volumes attached to the instances
* smartly fetching Floating IPs available in a vm network before triggering the job

**Comment by XDsubhash** [comment]
* currently: we can use the openstack cli to check available IPs:
  * openstack ip availability list | grep -e _cci_ -e shared
* each suite trigger might need on average around 15-20 IPs

**Comment by XDsubhash** [comment]
vol cleanup error: https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-ansible-sanity-4.1-rhel7.8/6/console
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-ansible-sanity-4.1-rhel8.1/15/console

**Comment by XDsubhash** [comment]
#93 should fix the cleanup issue

**Comment by XDsubhash** [comment]
#93 increase timeout to 25 seconds after detaching volume (volumes are in available state)  https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-ansible-sanity-4.1-rhel7.8/37/console

**Comment by XDsubhash** [comment]
if we are still hitting volume cleanup issues, will remove parallel execution.

**Comment by psathyan** [comment]
The refactoring effort carried out as part of #379 takes care of detaching the floating IP address before the VM is removed. Currently, floating IP address are not assigned. Closing this issue.
