### ISSUE TITLE
change vm flavors in conf file 

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#82]
* Better use of resources in osp env 
 * change vm flavors of some time consuming suites like 
    - [ ] cephfs 
    - [ ]  rbd-mirror
    - [ ] ansible

**Comment by XDsubhash** [comment]
Almost hitting resource limit in osp , need to reconsider which suites shud have priority

**Comment by psathyan** [comment]
We have a come long way from here... now, the suites are made smaller and their are split based on tiers. Along with these, more resources have been added to the environment to help sustain parallel execution. 

This strategy has helped us use the resources better hence closing this issue for now.

PS: We would still hit over consumption that would need to be addressed at that time frame.
