### ISSUE TITLE
[RFE] Option to start tests with debug set to particular level

### ISSUE THREAD

**Issue by veera-raghava-reddy** [red-hat-storage/cephci#837]
When tests fail in Automation, there is a need to attach debug logs to the bugs. Need an option to rerun failed tests with debug enabled and capture logs per tests and attach to the particular bug or collect and archive in manga002 for linking to bug.

**Comment by psathyan** [comment]
@veera-raghava-reddy IMO, it becomes a costly affair (in terms of resources and time) if we plan to rerun the tests on failure. At present, we are running tests in debug mode and the logs are pushed to a centralized location in the pipeline. However, the cluster is set to default logging mode.

In the next release, we are working on pushing the logs of cluster to a log stash. If things go as well, we could look into moving the cluster logging to debug mode.

**Comment by pdhiran** [comment]
@veera-raghava-reddy , are we looking for a method that changes the default logging level for various components like mgr, mon, osd at the beginning of test? like changing the logging levels is the 1st test run in the suite, something like this ( based on the components passed):
```   - test:
      name: Change logging levels 
      module: rados_prep.py
      config:
          configurations:
            - config-1:
                section: "global"
                name: "debug_mgr"
                value: "10/10"
            - config-2:
                section: "global"
                name: "debug_osd"
                value: "20/20"
```
Or something like a flag set during cluster deployment which will change the logging levels without addition of the above test in the test suite?

All cluster logs would still need this script [1] to collect and place in magna. 
[1] . https://github.com/red-hat-storage/cephci/blob/master/collect_logs.py

Also, if we run tests with increased debug, the root partition for each host needs to be increased or aggressive log rotation needs to be implemented, as if  root gets filled up, cluster starts misbehaving.
