### ISSUE TITLE
rbd cli suite fix for nautilus. py2 to py3 conversion

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#86]
* suites/nautilus/rbd/sanity_containerized_rbd.yaml
* suites/nautilus/rbd/sanity_rbd.yaml

Above suites currently fail ,needs py2 to py3 and nautilus support.
Fix it here: https://github.com/red-hat-storage/ceph-qe-scripts/tree/master/rbd and run the suite from cephci.

**Comment by XDsubhash** [comment]
few errors
```
python 3 port
 
xrange to range 
decode bytes to str
dict >itermitems() to items()

Traceback (most recent call last):
  File "rbd_cli_image.py", line 61, in <module>
    for iterator, param in enumerate(combinations, start=iterator + 1)]
NameError: name 'iterator' is not defined

format 1 completely deprecated
fastdiff objet map link enable disable
```

**Comment by XDsubhash** [comment]
@Gopi-Patta any update on this?can you send a draft PR (WIP) so we can dicuss in github if you are facing any issue in fixing

**Comment by harishmunjulur** [comment]
https://github.com/red-hat-storage/ceph-qe-scripts/pull/31

rbd_cli_snap_clone.py has been modified to work with Py3

**Comment by harishmunjulur** [comment]
https://github.com/red-hat-storage/ceph-qe-scripts/pull/34

making rbd/utils/utils.py py3 compatible.

**Comment by harishmunjulur** [comment]
https://github.com/red-hat-storage/ceph-qe-scripts/pull/35

making rbd/utils/log.py py3 compatible.

**Comment by harishmunjulur** [comment]
https://github.com/red-hat-storage/ceph-qe-scripts/pull/36

Adding the RHCS 4 parameters and making required changes for py3 compatible (rbd/system/cli/parameters.py)

**Comment by XDsubhash** [comment]
@harishmunjulur @Gopi-Patta can you post logs for rhcs3 and rhcs4?

**Comment by Gopi-Patta** [comment]
Added logs.

**Comment by XDsubhash** [comment]
can you post whole suite passed logs for rhcs3,4? it shud take an around an hr.
If possible for containers too

**Comment by XDsubhash** [comment]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1591004026078/test_83572722_0.log who's working on this failure?

**Comment by harishmunjulur** [comment]
Hi @XDsubhash I am working on  http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1591004026078/test_83572722_0.log. Its still work in progress.

**Comment by harishmunjulur** [comment]
I have completed working on this file. http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1591004026078/test_83572722_0.log. have sent the PR red-hat-storage/ceph-qe-scripts#36

**Comment by harishmunjulur** [comment]
WIP- Complete logs for sanity and sanity_containerized.

**Comment by harishmunjulur** [comment]
red-hat-storage/ceph-qe-scripts#36

This PR has all the changes I have made. 

LOGS:
Luminous : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1592366482717/
Nautilus: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1592348052581/

**Comment by harishmunjulur** [comment]
This has been tested and everything passes. Moving it to close
