### ISSUE TITLE
shrink-osd playbook  is failing in ceph ansible container suite (4.0-rhel-8)

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#87]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/RHCS%20Sanity/job/rhceph-sandbox-1/3/console 

looking for  mon container in hosts file , which was removed earlier in the suite(by shrink-mon )
https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/shrink-osd.yml#L26

should we remove from the hosts file too or ansible shud do it?

**Comment by XDsubhash** [comment]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/RHCS%20Sanity/job/rhceph-sandbox-1/8/console passed case

**Comment by VasishtaShastry** [comment]
@XDsubhash ,

> should we remove from the hosts file too or ansible shud do it?
After we shrink and role from a node, it should be the responsibility of the user to remove the node from the inventory file, ansible wouldn't be doing it

**Comment by XDsubhash** [comment]
@VasishtaShastry any idea why it might be passing in some scenarios?

**Comment by XDsubhash** [comment]
@Ameenasuhani pls do rca

**Comment by XDsubhash** [comment]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/rhceph-containerized-ceph-ansible-sanity-4.1-rhel7.8/16/console

**Comment by Ameenasuhani** [comment]
@XDsubhash RCA. .The shrink-osd playbook fails as recommendations have changed for 4.x [1].
we need to directly run "ansible-playbook -v infrastructure-playbooks/shrink-osd.yml -e osd_to_kill=OSD_ID" and the copying step needs to be skipped[2].
[1]https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/4/html/administration_guide/osd-bluestore#tuning-ceph-bluestore-for-small-writes_admin
[2]https://github.com/red-hat-storage/cephci/blob/master/tests/shrink_osd.py#L41

**Comment by XDsubhash** [comment]
resolved with  #169
