### ISSUE TITLE
purge cluster fails in most of suites

### ISSUE THREAD

**Issue by subhashp7i** [red-hat-storage/cephci#88]
* tests/purge_cluster.py fails with ssh errors

**Comment by XDsubhash** [comment]
need to do rca , Intermittent.

**Comment by Ameenasuhani** [comment]
@XDsubhash RCA.The purge fails as recommendations have changed for 4.x [1].
we need to directly run "ansible-playbook infrastructure-playbooks/purge-cluster.yml" and the copying step needs to be skipped[2].

[1]https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/4/html/installation_guide/purging-storage-clusters-deployed-by-ansible-install
[2]https://github.com/red-hat-storage/cephci/blob/master/tests/purge_cluster.py#L58

**Comment by XDsubhash** [comment]
thanks @Ameenasuhani for pointing out 4.x changes, will include them

I believe this intermittent issue was seen even in 3.x. whenever someone see purge cluster fails they can update logs here

**Comment by psathyan** [comment]
__Update__
Will need to follow with Sunil to gather information on the failure cases. Attempt to close on this issue if we have 4.x priority test suites failing.

**Comment by psathyan** [comment]
With the new approach of test suites, we are no longer using `purge_cluster` in our runs. Closing this issue.
