### ISSUE TITLE
long running commands stuck in fs suite

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#90]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/CEPH4.1-RHEL8-Features/detail/CEPH4.1-RHEL8-Features/1/pipeline/5/

* some test cases get stuck forever in fs suite at cmds like "rm -rf " in clean steps.

debug: Initial pointers check if cluster is getting filled becasue of more IOs/ increase the the vm flavor for more ram and try.

* Blocking the whole pipeline p1 jobs triggered weekly ..For now set a timer in script to avoid blocking  remaining suite and pipeline indefinitely.

**Comment by yogesh-mane** [comment]
@XDsubhash , I didn't face commands getting stuck issue.
Instead testcase CEPH-11255_11336_fuse as mentioned in https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/CEPH4.1-RHEL8-Features/detail/CEPH4.1-RHEL8-Features/1/pipeline/5/ is getting failed for other issue.
Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/
Logs for testcase CEPH-11255_11336_fuse: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/OSD-failure_0.log

**Comment by XDsubhash** [comment]
@yogesh-mane what is the other issue ?

i see 7 scripts failed here: Logs: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/
you have to make sure this suite passes , make sure  all tests pass in 4.1-rhel7,4.1-rhel8,3.3

1)http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/cephfs-split-merge_0.log
2)http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/cephfs-stressIO_0.log
3)http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/OSD-failure_0.log
4)http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/MDS-pinning-system_tests_0.log
5) http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/cephfs-rsync_0.log
6)http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/cephfs-basics_0.log
7)http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1589189356737/client-eviction_0.log

if you look at last 3 weekends pipeline job in jenkins they do get stuck for 2_3days i had to manually wait and cancel them over weekend (which is not feasible) so it wont block the  jslave and other jobs . As mentioned in description you can add a timeout for those long running commands and fix above script issues

**Comment by XDsubhash** [comment]
@yogesh-mane  any update on this?can you send a draft PR (WIP) so we can dicuss in github if you are facing any issue in fixing

**Comment by yogesh-mane** [comment]
>@yogesh-mane what is the other issue ?

@XDsubhash  , I see following failure for  testcase CEPH-11255_11336_fuse

2020-05-11 17:51:24,632 - CEPH-11255_11336_fuse - INFO - pgrep -u ceph osd  Error:  pgrep: invalid user name: ceph
 10.0.102.249
2020-05-11 17:51:24,635 - CEPH-11255_11336_fuse - INFO - Traceback (most recent call last):
  File "/home/ymane/c/cephci/tests/cephfs/CEPH-11255_11336_fuse.py", line 276, in run
    fs_util.pid_kill(node, 'osd')
  File "/home/ymane/c/cephci/tests/cephfs/cephfs_utils.py", line 1265, in pid_kill
    out, rc = node.exec_command(cmd='pgrep -u ceph %s ' % (daemon))
  File "/home/ymane/c/cephci/ceph/ceph.py", line 1632, in exec_command
    **kw) if self.containerized else self.node.exec_command(cmd=cmd, **kw)
  File "/home/ymane/c/cephci/ceph/ceph.py", line 1173, in exec_command
    raise CommandFailed(kw['cmd'] + " Error:  " + str(stderr.read().decode()) + ' ' + str(self.ip_address))
ceph.ceph.CommandFailed: pgrep -u ceph osd  Error:  pgrep: invalid user name: ceph

>As mentioned in description you can add a timeout for those long running commands and fix above script issues

I can add timeout, but all these testcases are failing cleanly for other errors & not getting stuck.

So should I start taking testcases one-by-one & fix them?

Because even if I add the timeout, I won't be able to test the fix because testcase would be failing for other error.

**Comment by XDsubhash** [comment]
> I can add timeout, but all these testcases are failing cleanly for other errors & not getting stuck.

If that is the case why did logs in description say running 2_3days?i wouldnt need to go cancel the suite manually

> So should I start taking testcases one-by-one & fix them?
yes!!
> Because even if I add the timeout, I won't be able to test the fix because testcase would be failing for other error.
timeout is temporary immediate fix if you need more time to fix the above 7 issues.i believe most of  them uses common cephfs utils right?

**Comment by yogesh-mane** [comment]
>If that is the case why did logs in description say running 2_3days?i wouldnt need to go cancel the suite manually
This is weird, because in my run I didn't face this issue.
Anyway I will work on adding timeout.
>timeout is temporary immediate fix if you need more time to fix the above 7 issues.
Got it.
>i believe most of them uses common cephfs utils right?
Need to check

**Comment by XDsubhash** [comment]
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/CEPH4.1-RHEL7-Features/detail/CEPH4.1-RHEL7-Features/4/pipeline
stuck for 6 days

**Comment by XDsubhash** [comment]
@yogesh-mane can you add the timeout to find cmds too?

Running command sudo find /mnt/cephfs_6ylu4pu7nj/ -type f -delete on 10.0.101.23

stuck for 2 days
https://ceph-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/CEPH4.1-RHEL7-Features/detail/CEPH4.1-RHEL7-Features/6/pipeline/

**Comment by yogesh-mane** [comment]
Sure @XDsubhash

**Comment by yogesh-mane** [comment]
@XDsubhash , I have already added timeout to sudo find  -type f -delete commands, not sure why its still getting stuck. I will debug on this.
