### ISSUE TITLE
rename docker cli args 

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#91]
1) --docker to --container, try maximum to  remove references to docker to avoid confusion
2) later update jenkins configs

**Comment by XDsubhash** [comment]
For triggering container runs on nightly images  remove cli arg“--ignore-latest-container”
(auto picks from http://magna002.ceph.redhat.com/cephci-jenkins/latest-rhceph-container-info/ , else specify reg ,image, tag manually with cli args)
if you specify --ignore-latest-container > then two options we have  1) to run rpm based suite 	2) to run container suite for that you need to specify container details , image ,tag ,reg manually with cli args along with it eg --docker-image --docker-reg etc
1) defaults
2) our choice
1) or 2) depends on the suite file you selected either containerized suite or rpm suite

**Comment by XDsubhash** [comment]
can work on this improvement when working on this issue.

improvement can be done to throw error at initial stage while selecting option1) or 2) in above comment (check if it effects all scenarios, need to clean up and order the code on registries picking can look at this priority
 1) default ansible conf
 2) umb json in magna002 ( override 1)
 3) --container cli arg (override 2) high priority

**Comment by psathyan** [comment]
At this moment, we don't plan to fix this issue as the impact is high.
