### ISSUE TITLE
podman support to rgw suite and s3 upstream tests

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#92]
*  rgw suite might needs couple fixes in ceph-qe-scripts to pass for container deployments(both podman and docker)
tests/sanity_rgw.py

* tests/test_s3.py --> fails always for baremetal too

* will fail jenkins p0 and cvp container jobs if any test need to be added 
#89

**Comment by XDsubhash** [comment]
do all tests use 8080 port?
inside 8.1 container image if we do [cephuser@ceph-7vp-1580208107235-node8-rgw ~]$ sudo docker exec ceph-rgw-ceph-7vp-1580208107235-node8-rgw-rgw0 sudo netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -                   
tcp        0      0 10.0.147.165:8080       0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -                   
tcp6       0      0 ::1:25                  :::*                    LISTEN      -                   
tcp6       0      0 :::111                  :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      -
if we do grep radosgw as per utils at rgw-tests/ceph-qe-scripts/rgw/v2/utils/utils.py
it's returning none
i guess in in rhcs3.3 it showed PID/name  not showing here(different for 4.x)
and also no netstat package in 8.1 container images..we can install manualy thou (for this we can edit sanity-rgw.py script)


not sure how many TC's use get_radosgw_port_no --> this function

**Comment by XDsubhash** [comment]
s3 upstream tests can be fixed later in another issue.

remaining tests need to work on container deployment with both podman and docker (rhcs3.x and rhcs4.x)
@rakeshgm  any update on this?should we assign it to anyone? it'll be better if its assigned to someone who sent PRs to ceph-qe-scripts repo @udaysk23 or @rpratap-bot may be?

**Comment by rakeshgm** [comment]
I think @udaysk23 can take it up. I will review it once he fixes it. assign it to him.

**Comment by rakeshgm** [comment]
we can take s3tests as a separate issue. This is a big fix that needs changes in s3tests repository too. we might not be able to fix this immediately. we need sync up with dev on this.

**Comment by udaysk23** [comment]
I will work on podman changes as suggested

**Comment by udaysk23** [comment]
https://github.com/red-hat-storage/cephci/pull/151

Above PR fixed this issue. Closing this issue now
