### ISSUE TITLE
Have latest cdn registry names in all suites and GAed deployment cli args

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#94]
* current ceph-ansible configs point to old cdn container registry ,image and tags (luminous and nautilus)https://github.com/red-hat-storage/cephci/blob/master/suites/nautilus/ansible/sanity_containerized_ceph_ansible.yaml#L26

**Comment by XDsubhash** [comment]
* we have cli args in cephci which help to deploy GAed versions of rhceph 3.x,4x(container/non-container) ,make sure it works by picking ansible config from suite yamls

**Comment by XDsubhash** [comment]
For container upgrades ,might need to sort this out first

**Comment by XDsubhash** [comment]
you can get proper names here : https://catalog.redhat.com/software/containers/search?p=1&product_listings_names=Red%20Hat%20Ceph%20Storage&rows=60

**Comment by sunilangadi2** [comment]
https://github.com/red-hat-storage/cephci/pull/182
This PR fixes CDN based installation using GAed registry login,
existing luminous works fine with this registry.access.redhat.com
https://github.com/red-hat-storage/cephci/pull/231 from this
nautilus container related suite uses correct ones in container upgrade
also we can pass GAed version docker details as well in ceph ci cli args.
Hence closed this issue.
