### ISSUE TITLE
review test case description and update 

### ISSUE THREAD

**Issue by XDsubhash** [red-hat-storage/cephci#95]
* Check ansible suites TC description and update them 
* review mixed lvm configs TC description and iso install

**Comment by psathyan** [comment]
IMO, we can close this issue as the newer test suites have sufficient descriptions. However, we would need a placeholder to ensure the executed test suites have a 1 x 1 Polarion ID. A missing Polarion ID shouldn't prevent us from merge but there should be an issue opened to ensure that it is added.

**Comment by psathyan** [comment]
Closing this issue for now. Let's have specific issues created for missing details or those test suites not adhering to the guidelines.
