### ISSUE TITLE
rados bench test failed saying pg_num would be too high

### ISSUE THREAD

**Issue by VasishtaShastry** [red-hat-storage/cephci#961]
ceph.ceph.CommandFailed: sudo ceph osd pool create test_pool640 128 Error:  Error ERANGE:  pg_num 128 size 3 would mean 840 total pgs, which exceeds max 750 (mon_max_pg_per_osd 250 * num_in_osds 3)
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-I1LXT2/rados_bench_test_0.log

**Comment by VasishtaShastry** [comment]
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-I1LXT2/Parallel_run_0.log

**Comment by pdhiran** [comment]
The feature due to which the PG's are maxing out is being rolled back. https://bugzilla.redhat.com/show_bug.cgi?id=2021738#c2

**Comment by pdhiran** [comment]
Issue fixed with build ` ceph-16.2.7-4.el8cp ` . The default profile of PG autoscaler changed back to ` scale-up ` from ` scale-down  `, due to whhhi we were hitting the PG upper bound limit.
