### ISSUE TITLE
lvm osd auto discovery TC

### ISSUE THREAD

**Issue by subhashp7i** [red-hat-storage/cephci#97]
* add lvm osd auto discovery TC to any of the suite

**Comment by XDsubhash** [comment]
@Ameenasuhani can you look into this

**Comment by XDsubhash** [comment]
add the same test_ansible script but change ansible config in suite yaml

**Comment by XDsubhash** [comment]
it's better to add to lvm_utils https://github.com/red-hat-storage/cephci/blob/master/utility/lvm_utils.py#L243 and have the scenario part of existing mixed_lvm_configs suites

**Comment by rakeshgm** [comment]
we can reopen this issue when we see more consistent failures.
