### ISSUE TITLE
enable fips by default

### ISSUE THREAD

**Issue by subhashp7i** [red-hat-storage/cephci#98]
* have fips enabled for all deployments (nautilus and luminous?)

**Comment by XDsubhash** [comment]
only nautilus

**Comment by XDsubhash** [comment]
enable in framework

**Comment by veera-raghava-reddy** [comment]
Need to have the option to run Tier1 with FIPS enabled.

**Comment by psathyan** [comment]
Adding this to the backlog for 2022 Q2

**Comment by sunilkumarn417** [comment]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/assembly_installing-a-rhel-8-system-with-fips-mode-enabled_security-hardening
